version: '3.9'

services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - frontend-build:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://Main_user:Sepio_password@sepio-app-mysql-1:3306/nodejs_login
    volumes:
      - backend-data:/app/data
      - frontend-build:/usr/share/nginx/html
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "
        npx prisma migrate deploy &&
        npm start
      "

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nodejs_login
      MYSQL_USER: Main_user
      MYSQL_PASSWORD: Sepio_password
      MYSQL_INITDB_SKIP_TZINFO: '1'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  frontend-build:
  backend-data:
  mysql: